arb-dir: lib/core/localization/l10n
template-arb-file: intl_ar.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: desiredFileName.txt
synthetic-package: false
output-dir: lib/core/localization/generated
